import Head from 'next/head'
import Portfolio from '../components/Portfolio'
import { Layout } from '../components/Layout'
import ContactForm from '../components/ContactForm.js'
import { News } from '../components/News'
import { withTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Header from '../components/Header'
import Services from '../components/Services'
import AboutUs from '../components/AboutUs'
import ContactButton from '../components/ContactButton'
function Home({ t }) {

  return (
    <>
      <Head>
        <title>Teo-Coop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ background: 'black' }}>
        <Layout>
          <Header />
          <div className='backgroundAmplio'>
            <Portfolio />
            <AboutUs />
            <Services />
            <News />
            <div style={{background:'#00000030', backdropFilter: 'blur(5px)', height: '100%', padding: '1rem', border: '1px solid #ffffff90', borderRadius: '10px', marginTop: '1rem', boxShadow: '#ffffff90 0px 0px 10px' }}>
              <ContactForm />
            </div>
          </div>
          <ContactButton />
        </Layout>
      </div>
    </>
  )
}


export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common',
        'header',
        'aboutUs',
        'services',
        'noticias',
        'contact',
        'navbar'
      ])),
      // Will be passed to the page component as props
    },
  }
}
export default withTranslation('common')(Home)
