import Head from 'next/head'
import { Header } from '../components/Header'
import Nosotros from '../components/cards/Nosotros'
import { Servicios } from '../components/Servicios'
import Portfolio from '../components/Portfolio'
import { Layout } from '../components/Layout'
import ContactForm from '../components/Contact'
import { Noticias } from '../components/Noticias'


export default function Home() {
  return (
    <>
      <Head>
        <title>Teo-Coop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ background: 'black' }}>
        <Layout>
          <Header />
          <div className='backgroundAmplio'>
          <Portfolio />
            <Nosotros />
            <Servicios />
            <Noticias/>
          </div>
          <ContactForm />
        </Layout>
      </div>
    </>
  )
}
